#!/usr/bin/env python

import rospy
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped


class PathPublisher:
    def __init__(self):
        rospy.init_node('path_node')
        pose_topic = rospy.get_param('pose_topic', '/slam_out_pose')
        path_topic = rospy.get_param('out_path_topic', '/path_pose')
        self._max_poses = rospy.get_param('max_poses', 50)

        self._pose_path = Path()
        self._pose_sub = rospy.Subscriber(pose_topic, PoseStamped,
                                          self._pose_callback, queue_size=1)
        self._pose_path_pub = rospy.Publisher(path_topic, Path, queue_size=10)

        rospy.loginfo("Started Path publisher")

        rospy.spin()

        rospy.loginfo("Stopped Path publisher")

    def _pose_callback(self, data):
        if len(self._pose_path.poses) == self._max_poses:
            self._pose_path.poses = self._pose_path.poses[1:]

        self._pose_path.poses.append(data)
        self._pose_path_pub.publish(self._pose_path)


if __name__ == '__main__':
    PathPublisher()
