#!/usr/bin/env python

import rospy
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped

class PathPublisher:
    def __init__(self):
        self._pose_path = Path()
        self._pose_sub = rospy.Subscriber('/slam_out_pose', PoseStamped,
                                          self._pose_callback, queue_size=1)
        self._pose_path_pub = rospy.Publisher('/path/pose', Path, queue_size=10)

    def _pose_callback(self, data):
        self._pose_path.poses.append(data)
        self._pose_path_pub.publish(self._pose_path)

rospy.init_node('path_node')

if __name__ == '__main__':
    PathPublisher()
    rospy.spin()
